// rankingDummy.js
export const rankingDummy = [
  {
    id: 1,
    season: "Season 2",
    rank: 1,
    tier: "그랜드마스터",
    nickname: "Nike",
    statusMessage: "책 좋아용",
    postCount: 199,
    likes: 431,
  },
  {
    id: 2,
    season: "Season 2",
    rank: 2,
    tier: "마스터",
    nickname: "Adidas",
    statusMessage: "...",
    postCount: 812,
    likes: 380,
  },
  {
    id: 3,
    season: "Season 2",
    rank: 3,
    tier: "다이아",
    nickname: "Vans",
    statusMessage: ":)",
    postCount: 153,
    likes: 317,
  },
  {
    id: 4,
    season: "Season 2",
    rank: 4,
    tier: "골드",
    nickname: "Converse",
    statusMessage: "컴퓨터구조, 알고리즘",
    postCount: 128,
    likes: 279,
  },
  {
    id: 5,
    season: "Season 2",
    rank: 5,
    tier: "실버",
    nickname: "Asics",
    statusMessage: "안녕하세요",
    postCount: 105,
    likes: 245,
  },
  {
    id: 11,
    season: "Season 1",
    rank: 1,
    tier: "그랜드마스터",
    nickname: "Player1",
    statusMessage: "Hello, I'm Player1!",
    postCount: 30,
    likes: 100,
  },
  {
    id: 12,
    season: "Season 1",
    rank: 2,
    tier: "마스터",
    nickname: "Player2",
    statusMessage: "Nice to meet you!",
    postCount: 25,
    likes: 90,
  },
];
