// bookDummy.js
export const bookDummy = [
  {
    id: 1,
    book_title: "코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    publish: "2023-01-01",
    image_file: "book_image_1.svg",
    vote: 14,
    vote_avg: 4.6,
    my_vote: 0,
    intro: "",
  },
  {
    id: 2,
    book_title: "플러터 앱 프로그래밍",
    author: "최지호 외 2명",
    publisher: "앤써북",
    publish: "2023-01-01",
    image_file: "book_image_222.svg",
    vote: 9,
    vote_avg: 4.1,
    my_vote: 0,
    intro: "",
  },
  {
    id: 3,
    book_title: "Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    publish: "2023-01-01",
    image_file: "book_image_333.svg",
    vote: 22,
    vote_avg: 4.8,
    my_vote: 0,
    intro: "",
  },
  {
    id: 4,
    book_title: "야간 비행 (강호남 시집)",
    author: "강호남",
    publisher: "천년의 시작",
    publish: "2022-01-01",
    image_file: "book_image_11.svg",
    vote: 14,
    vote_avg: 4.6,
    my_vote: 0,
    intro: "",
  },
  {
    id: 5,
    book_title: "야간 비행",
    author: "생택쥐페리",
    publisher: "지경사",
    publish: "2010-01-01",
    image_file: "book_image_22.svg",
    vote: 9,
    vote_avg: 4.1,
    my_vote: 0,
    intro: "",
  },
  {
    id: 6,
    book_title: "야간 비행",
    author: "생택쥐페리",
    publisher: "더클래식",
    publish: "2021-01-01",
    image_file: "book_image_33.svg",
    vote: 22,
    vote_avg: 4.8,
    my_vote: 3.5,
    intro:
      "1931년 페미나 문학상 수상, 생텍쥐페리 행동주의 문학의 대표작 《야간 비행》 노벨 문학상 수상작가 앙드레 지드의 서문 수록\n\n[줄거리] 야간 비행이 시작된 초창기 비행사들은 열악한 장비에도 불구하고 험난한 비행을 용감하게 수행해 냈다. 그들은 비행기에 우편물을 가득 싣고 너른 바다와 높은 산을 넘어 목적지로 날아갔다. 그들, 용감한 비행사들 중 하나였던 파비앵은 파타고니아 비행장에서 출발해 아름다운 저녁노을을 지나 부에노스아이레스를 향해 날아가고 있었다. 부에노스아이레스에서는 그가 가져오는 우편물을 싣고 다시 유럽으로 떠날 우편기가 기다렸다.",
  },
];
