const SentimentDetailDummy = [
    {
        id:1,
        title: '플러터 프로그래밍 책 후기',
        book: 'Must Have 코드팩토리의 플러터 프로그래밍',
        author: '(최지호/골든래빗)',
        name: 'Paul',
        tier: "그랜드마스터",
        date: '23/12/18(월요일) 15:05',
        imagefile: "book_image_1.svg",
        star: '★★★★★ 5.0',
        insertImg: "insert_Img.png",
        text: '플러터 프로그래밍을 인강이 아닌 책으로 배워봤다.\n이 책에서는 플러터를 포함하여 Dart언어와 Firebase를 추가로 알려준다.\n640페이지의 많은 양으로 자세히 배울 수 있다.', 
    },
    {
        id:2,
        title: '파이썬 프로그래밍 공부',
        book: '혼자 공부하는 파이썬',
        author: '(윤인성/한빛미디어)',
        name: 'kyle654321',
        tier: "마스터",
        date: '23/12/18(월요일) 15:05',
        imagefile: 'book_image_2.svg',
        star: '★★★★ 4.0',
        insertImg: 'insert_Img.png',
        text: '파이썬 프로그래밍 공부 센티멘트 내용', 
    },
    {
        id:3,
        title: 'JS 백엔드 개발 차이점 (프로그래밍)',
        book: 'Do It! Node.js 프로그래밍 입문',
        author: '(고경희/이지스퍼블리싱)',
        name: 'Jenny99',
        tier: "다이아",
        date: '23/12/18(월요일) 15:05',
        imagefile: 'book_image_3.svg',
        star: '★★★★ 4.0',
        insertImg: 'insert_Img.png',
        text: '플러터 프로그래밍을 인강이 아닌 책으로 배워봤다.\n이 책에서는 플러터를 포함하여 Dart언어와 Firebase를 추가로 알려준다.\n640페이지의 많은 양으로 자세히 배울 수 있다.', 
    },
]
export default SentimentDetailDummy;