// sentimentDummy.js
export const sentimentDummy = [
  {
    id: 1,

    sentiment_title: "플러터 프로그래밍 후기",
    book_title: "Must Have 코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    nickname: "Paul",
    tier: "그랜드마스터",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_1.svg",
    rating: 5.0,
  },
  {
    id: 2,
    sentiment_title: "파이썬 프로그래밍 공부",
    book_title: "혼자 공부하는 파이썬",
    author: "윤인성",
    publisher: "한빛미디어",
    nickname: "kyle654321",
    tier: "마스터",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_2.svg",
    rating: 4.0,
  },
  {
    id: 3,
    sentiment_title: "JS 백앤드 개발 차이점 (프로그래밍)",
    book_title: "Do it! Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    nickname: "Jenny99",
    tier: "다이아",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_3.svg",
    rating: 4.0,
  },
  {
    id: 4,
    sentiment_title: "플러터 프로그래밍 후기2",
    book_title: "Must Have 코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    nickname: "Paul",
    tier: "루키",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_1.svg",
    rating: 5.0,
  },
  {
    id: 5,
    sentiment_title: "파이썬 프로그래밍 공부2",
    book_title: "혼자 공부하는 파이썬",
    author: "윤인성",
    publisher: "한빛미디어",
    nickname: "kyle654321",
    tier: "실버",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_2.svg",
    rating: 4.0,
  },
  {
    id: 6,
    sentiment_title: "JS 백앤드 개발 차이점 (프로그래밍)2",
    book_title: "Do it! Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    nickname: "Jenny99",
    tier: "골드",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_3.svg",
    rating: 4.0,
  },
  {
    id: 7,
    sentiment_title: "플러터 프로그래밍 후기3",
    book_title: "Must Have 코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    nickname: "Paul",
    tier: "마스터",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_1.svg",
    rating: 5.0,
  },
  {
    id: 8,
    sentiment_title: "파이썬 프로그래밍 공부3",
    book_title: "혼자 공부하는 파이썬",
    author: "윤인성",
    publisher: "한빛미디어",
    nickname: "kyle654321",
    tier: "루키",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_2.svg",
    rating: 4.0,
  },
  {
    id: 9,
    sentiment_title: "JS 백앤드 개발 차이점 (프로그래밍)3",
    book_title: "Do it! Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    nickname: "Jenny99",
    tier: "다이아",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_3.svg",
    rating: 4.0,
  },
  {
    id: 10,
    sentiment_title: "플러터 프로그래밍 후기4",
    book_title: "Must Have 코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    nickname: "Paul",
    tier: "루키",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_1.svg",
    rating: 5.0,
  },
  {
    id: 11,
    sentiment_title: "파이썬 프로그래밍 공부4",
    book_title: "혼자 공부하는 파이썬",
    author: "윤인성",
    publisher: "한빛미디어",
    nickname: "kyle654321",
    tier: "골드",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_2.svg",
    rating: 4.0,
  },
  {
    id: 12,
    sentiment_title: "JS 백앤드 개발 차이점 (프로그래밍)4",
    book_title: "Do it! Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    nickname: "Jenny99",
    tier: "그랜드마스터",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_3.svg",
    rating: 4.0,
  },
  {
    id: 13,
    sentiment_title: "플러터 프로그래밍 후기5",
    book_title: "Must Have 코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    nickname: "Paul",
    tier: "골드",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_1.svg",
    rating: 5.0,
  },
  {
    id: 14,
    sentiment_title: "파이썬 프로그래밍 공부5",
    book_title: "혼자 공부하는 파이썬",
    author: "윤인성",
    publisher: "한빛미디어",
    nickname: "kyle654321",
    tier: "루키",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_2.svg",
    rating: 4.0,
  },
  {
    id: 15,
    sentiment_title: "JS 백앤드 개발 차이점 (프로그래밍)5",
    book_title: "Do it! Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    nickname: "Jenny99",
    tier: "마스터",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_3.svg",
    rating: 4.0,
  },
  {
    id: 16,
    sentiment_title: "플러터 프로그래밍 후기6",
    book_title: "Must Have 코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    nickname: "Paul",
    tier: "그랜드마스터",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_1.svg",
    rating: 5.0,
  },
  {
    id: 17,
    sentiment_title: "파이썬 프로그래밍 공부6",
    book_title: "혼자 공부하는 파이썬",
    author: "윤인성",
    publisher: "한빛미디어",
    nickname: "kyle654321",
    tier: "마스터",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_2.svg",
    rating: 4.0,
  },
  {
    id: 18,
    sentiment_title: "JS 백앤드 개발 차이점 (프로그래밍)6",
    book_title: "Do it! Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    nickname: "Jenny99",
    tier: "다이아",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_3.svg",
    rating: 4.0,
  },
  {
    id: 19,
    sentiment_title: "플러터 프로그래밍 후기7",
    book_title: "Must Have 코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    nickname: "Paul",
    tier: "루키",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_1.svg",
    rating: 5.0,
  },
  {
    id: 20,
    sentiment_title: "파이썬 프로그래밍 공부7",
    book_title: "혼자 공부하는 파이썬",
    author: "윤인성",
    publisher: "한빛미디어",
    nickname: "kyle654321",
    tier: "실버",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_2.svg",
    rating: 4.0,
  },
  {
    id: 21,
    sentiment_title: "JS 백앤드 개발 차이점 (프로그래밍)7",
    book_title: "Do it! Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    nickname: "Jenny99",
    tier: "골드",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_3.svg",
    rating: 4.0,
  },
  {
    id: 22,
    sentiment_title: "플러터 프로그래밍 후기8",
    book_title: "Must Have 코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    nickname: "Paul",
    tier: "마스터",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_1.svg",
    rating: 5.0,
  },
  {
    id: 23,
    sentiment_title: "파이썬 프로그래밍 공부8",
    book_title: "혼자 공부하는 파이썬",
    author: "윤인성",
    publisher: "한빛미디어",
    nickname: "kyle654321",
    tier: "루키",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_2.svg",
    rating: 4.0,
  },
  {
    id: 24,
    sentiment_title: "JS 백앤드 개발 차이점 (프로그래밍)8",
    book_title: "Do it! Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    nickname: "Jenny99",
    tier: "다이아",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_3.svg",
    rating: 4.0,
  },
  {
    id: 25,
    sentiment_title: "플러터 프로그래밍 후기9",
    book_title: "Must Have 코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    nickname: "Paul",
    tier: "루키",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_1.svg",
    rating: 5.0,
  },
  {
    id: 26,
    sentiment_title: "파이썬 프로그래밍 공부9",
    book_title: "혼자 공부하는 파이썬",
    author: "윤인성",
    publisher: "한빛미디어",
    nickname: "kyle654321",
    tier: "골드",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_2.svg",
    rating: 4.0,
  },
  {
    id: 27,
    sentiment_title: "JS 백앤드 개발 차이점 (프로그래밍)9",
    book_title: "Do it! Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    nickname: "Jenny99",
    tier: "그랜드마스터",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_3.svg",
    rating: 4.0,
  },
  {
    id: 28,
    sentiment_title: "플러터 프로그래밍 후기10",
    book_title: "Must Have 코드팩토리의 플러터 프로그래밍",
    author: "최지호",
    publisher: "골든래빗",
    nickname: "Paul",
    tier: "골드",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_1.svg",
    rating: 5.0,
  },
  {
    id: 29,
    sentiment_title: "파이썬 프로그래밍 공부10",
    book_title: "혼자 공부하는 파이썬",
    author: "윤인성",
    publisher: "한빛미디어",
    nickname: "kyle654321",
    tier: "루키",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_2.svg",
    rating: 4.0,
  },
  {
    id: 30,
    sentiment_title: "JS 백앤드 개발 차이점 (프로그래밍)10",
    book_title: "Do it! Node.js 프로그래밍 입문",
    author: "고경희",
    publisher: "이지스퍼블리싱",
    nickname: "Jenny99",
    tier: "마스터",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_3.svg",
    rating: 4.0,
  },
  {
    id: 31,
    sentiment_title: "계속 하늘을 날고 있을 어린왕자를 생각하며...",
    book_title: "야간 비행 / 남방 우편기",
    author: "생택쥐페리",
    publisher: "펭귄클래식코리아",
    nickname: "Paul",
    tier: "그랜드마스터",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_111.svg",
    rating: 5.0,
  },
  {
    id: 32,
    sentiment_title: "야간비행을 읽고",
    book_title: "야간 비행",
    author: "생택쥐페리",
    publisher: "더클래식",
    nickname: "kyle654321",
    tier: "마스터",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_33.svg",
    rating: 4.0,
  },
  {
    id: 33,
    sentiment_title: "야간 비행의 위험과 고독, 낭만 그리고 선택",
    book_title: "야간 비행",
    author: "생택쥐페리",
    publisher: "더클래식",
    nickname: "Jenny99",
    tier: "다이아",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_33.svg",
    rating: 4.0,
  },
  {
    id: 34,
    sentiment_title: "야간비행",
    book_title: "야간 비행",
    author: "생택쥐페리",
    publisher: "더클래식",
    nickname: "Paul",
    tier: "그랜드마스터",
    likes: 1231,
    comments: 321,
    bookmarks: 12,
    datetime: "2023-12-23 08:01:00",
    image_file: "book_image_33.svg",
    rating: 5.0,
  },
  {
    id: 35,
    sentiment_title: "별빛으로 물든 밤",
    book_title: "야간 비행",
    author: "생택쥐페리",
    publisher: "더클래식",
    nickname: "kyle654321",
    tier: "마스터",
    likes: 532,
    comments: 64,
    bookmarks: 9,
    datetime: "2023-12-23 06:59:00",
    image_file: "book_image_33.svg",
    rating: 4.0,
  },
  {
    id: 36,
    sentiment_title: "리비에르에 대해서",
    book_title: "야간 비행",
    author: "생택쥐페리",
    publisher: "더클래식",
    nickname: "Jenny99",
    tier: "다이아",
    likes: 101,
    comments: 12,
    bookmarks: 5,
    datetime: "2023-12-23 05:40:00",
    image_file: "book_image_33.svg",
    rating: 4.0,
  },
];
