// sentimentDummy.js
export const sentimentDummy = [
  {
    id: 1,
    title: "책 제목 1",
    subtitle: "소제목 1",
    author: "저자 1",
    publisher: "11",
    nickname: "abc1",
    tier: "골드",
    likes: 100,
    comments: 50,
    bookmarks: 30,
    date: "2024-01-15",
    time: "10:30 AM",
    image: "book_image_1.jpg",
    rating: 5.0,
  },
  {
    id: 2,
    title: "책 제목 2",
    subtitle: "소제목 2",
    author: "저자 2",
    publisher: "22",
    nickname: "abc2",
    tier: "실버",
    likes: 100,
    comments: 50,
    bookmarks: 30,
    date: "2024-01-15",
    time: "10:30 AM",
    image: "book_image_1.jpg",
    rating: 4.0,
  },
];
